### PR TITLE
Build with a recent version of the network package

### PR DESCRIPTION
**Pull request by gbrsales**
Small fixes to make the package build again after some changes in `network` and `network-bsd`.

### CODE REVIEW

**Comment by ysangkok** [comment]
@jgoerzen The package doesn't build with GHC 8.10, I believe this patch fixes it.

**Comment by jgoerzen** [comment]
Would you be interested in taking over maintaining this package?  I no longer use it.

**Comment by ysangkok** [comment]
@jgoerzen Not sure who you are asking, but yes, I would be interested in taking over maintainership. I would try to look into migrating off the MissingH dependency since it is unmaintained, and also making sure it runs on newer GHC releases. We are also looking into extended passive mode. My hackage user name is "janus". They told me they will add me to the Uploaders group if I am listed as maintainer for the package.

**Comment by jgoerzen** [comment]
That sounds great.  So I need to make a final upload listing you as a maintainer?  What will the new homepage for it be?

**Comment by ysangkok** [comment]
@jgoerzen Yes, please list me as maintainer, then I will ask the Hackage moderators for uploader permission. I just forked the repo to https://github.com/ysangkok/ftphs , I think that should serve fine as the new home. Then people will also be able to find it using the fork explorer GitHub has.

**Pull request merged**
